# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run my awesome tests

on:
  schedule:
    - cron:  '20 4 * * *'
  push:
    branches: [ "main" ]

jobs:
  run_tests:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
       node-version: '20.x'
    - name: Create env file
      run: |
        echo "${{secrets.MY_ENV }}" > .env
    - run: npm ci
    - run: npm run test
    - name: send default message to telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
